### ISSUE TITLE
[REQUEST] RBAC and OIDC support

### ISSUE THREAD

**Issue by zakka258** [realodix/urlhub#1000]
Could you add RBAC (Role Based Access Control)? Like admin can view all link and manage setting, editor only can create, view and manage link he create.

It would lovely if this can integrate seamlessly with OIDC provider like keycloak.

Thanks in advance.

**Comment by realodix** [comment]
> Could you add RBAC (Role Based Access Control)? Like admin can view all link and manage setting, editor only can create, view and manage link he create.

UrlHub already has it.

> It would lovely if this can integrate seamlessly with OIDC provider like keycloak.

No plans for this, at least in the near future.
