### ISSUE TITLE
The data is not displayed in the manager.

### ISSUE THREAD

**Issue by Terrorboy** [realodix/urlhub#730]
![urlhub](https://user-images.githubusercontent.com/5427199/92832968-45279780-f413-11ea-90e9-3dab53317f76.png)
-No console error
-Network tap data call complete

* The same symptom occurred in 'All URLs', 'All Users'

**Comment by Terrorboy** [comment]
![hub](https://user-images.githubusercontent.com/5427199/92835190-e6175200-f415-11ea-8928-84b679994a4f.png)

I changed it like an image and processed it.

**Comment by realodix** [comment]
In the screenshot, I saw the status stopped at "Processing".

Sorry, I cannot reproduce this issue. Data is processed and displayed as expected.

**Comment by Terrorboy** [comment]
- urlhub version: latest(5e891df)
- phpinfo: https://z9n.net/bm.php
- DB: MariaDB 10.3.24
- nginx setting:
```
server {
    listen       80;
    server_name o0o.st www.o0o.st;
    return 301 https://$host$request_uri;
}
server {
    listen       443 ssl http2;
    server_name o0o.st www.o0o.st;
    root    /home/workspace/url/public/;
    index index.php;

    ssl_certificate "/etc/letsencrypt/live/o0o.st/fullchain.pem";
    ssl_certificate_key "/etc/letsencrypt/live/o0o.st/privkey.pem";
    ssl_dhparam "/etc/ssl/certs/dhparam.pem";

    add_header Strict-Transport-Security "max-age=31536000";

    # Set caches, protocols, and accepted ciphers. This config will merit an A+ SSL Labs score.
    ssl_session_cache shared:SSL:20m;
    ssl_session_timeout 10m;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_prefer_server_ciphers on;
    ssl_ciphers 'ECDH+AESGCM:ECDH+AES256:ECDH+AES128:DH+3DES:!ADH:!AECDH:!MD5';

    location / {
        try_files $uri $uri/ /index.php?/$args;
    }

    location ~ \.php$ {
        fastcgi_split_path_info ^(.+?\.php)(/.*)$;
        fastcgi_pass unix:/run/php/php7.4-fpm.sock;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }
}
```


![urlhub](https://user-images.githubusercontent.com/5427199/93008695-7d191100-f5b2-11ea-92c3-401ad2185fb1.png)

**Comment by Terrorboy** [comment]
![urlhub2](https://user-images.githubusercontent.com/5427199/93009045-de42e380-f5b6-11ea-959f-30f3af5322c7.png)

What more information do you need?

**Comment by realodix** [comment]
I wrote several tests on this issue, all of which passed the test.

**Test**
[#738/files#diff-3dee2ee](https://github.com/realodix/urlhub/pull/738/files#diff-3dee2ee08c38262e1397e7223138071a)

**Result** 
https://github.com/realodix/urlhub/runs/1112259617

**Comment by Terrorboy** [comment]
We will prepare and test a new server in a short time.

**Comment by realodix** [comment]
Since it is related to datatables and server-side is implemented through the laravel-datatables, I think you could report to [yajra/laravel-datatables](https://github.com/yajra/laravel-datatables).

**Comment by Terrorboy** [comment]
I will report to yajra/laravel-datatables

Thank you!
