### ISSUE TITLE
How can I fix the error "Undefined array key 1"

### ISSUE THREAD

**Issue by pramuan** [realodix/urlhub#883]
ErrorException 

  Undefined array key 1

  at C:\urlhub\vendor\laravel\framework\src\Illuminate\Foundation\Console\ServeCommand.php:309
    305▕             : '/^\[([^\]]+)\]/';
    306▕
    307▕         preg_match($regex, $line, $matches);
    308▕
  ➜ 309▕         return Carbon::createFromFormat('D M d H:i:s Y', $matches[1]);
    310▕     }
    311▕
    312▕     /**
    313▕      * Get the request port from the given PHP server output.

  1   C:\urlhub\vendor\laravel\framework\src\Illuminate\Foundation\Console\ServeCommand.php:309
      Illuminate\Foundation\Bootstrap\HandleExceptions::Illuminate\Foundation\Bootstrap\{closure}("Undefined array key 1", "C:\urlhub\vendor\laravel\framework\src\Illuminate\Foundation\Console\ServeCommand.php")

  2   C:\urlhub\vendor\laravel\framework\src\Illuminate\Foundation\Console\ServeCommand.php:255
      Illuminate\Foundation\Console\ServeCommand::getDateFromLine(" Feb 17 19:53:16 2023] 10.8.50.18:51838 Accepted")

**Comment by realodix** [comment]
Steps To Reproduce?
