### ISSUE TITLE
[BUG] Is `AllUlrTable.php` a typo?

### ISSUE THREAD

**Issue by xiaohuilam** [realodix/urlhub#914]
**Describe the bug**
Is [AllUlrTable.php](https://github.com/realodix/urlhub/blob/e1dd2ba/app/Livewire/Table/AllUlrTable.php) a typo? it should be `AllUrlTable.php` by my understanding.
Can we correct if it is? to reduce further ambiguities。

**Comment by realodix** [comment]
You're right, it was a typo
