### ISSUE TITLE
[BUG] Display error when target page title is charset gb2312 (a different charset vs utf-8)

### ISSUE THREAD

**Issue by xiaohuilam** [realodix/urlhub#922]
<img width="498" alt="image" src="https://github.com/realodix/urlhub/assets/6964962/7fd00a2b-f977-4084-80e0-c647ebe57fdc">

<img width="357" alt="image" src="https://github.com/realodix/urlhub/assets/6964962/12239282-0abf-4271-a98d-491188e406eb">

**Comment by realodix** [comment]
https://github.com/realodix/urlhub/blob/772aa0007b3043d1bc5225c39e15c0e9bd12c1d1/app/Services/UHubLinkService.php#L65

It looks like the embed failed to deal with the encoding issue.

You can create an issue at https://github.com/oscarotero/Embed/issues

**Comment by xiaohuilam** [comment]
> https://github.com/realodix/urlhub/blob/772aa0007b3043d1bc5225c39e15c0e9bd12c1d1/app/Services/UHubLinkService.php#L65
> 
> It looks like the embed failed to deal with the encoding issue.
> 
> You can create an issue at https://github.com/oscarotero/Embed/issues

Thanks for pointing out the dependencies.

by my understanding, `oscarotero/Embed` provided some methods to crawl page url and pick up title or meta property from them. But it doesn't know which encoding charset the value return should be, because it depends the database configuration, and application HTML base layout defination.

I think this should be fixed by calling a native method `mb_convert_encoding` after `oscarotero/Embed` returned the title.

I do appreciate for you open sourced this powerful application.

- demo `gb2312` URL: `https://www.qq.com`.

**Comment by realodix** [comment]
If you want to work on PR to fix it, it's very appreciated

**Comment by xiaohuilam** [comment]
> If you want to work on PR to fix it, it's very appreciated

OK, I'll see how to checkout a new branch in my repo to get involved of this.
