### ISSUE TITLE
[BUG] Call to undefined method Livewire\LivewireManager::styles()

### ISSUE THREAD

**Issue by lionslair** [realodix/urlhub#951]
**Describe the bug**
Trying to access the admin with a fresh install.

**To Reproduce**
1. Perform the setup steps
2. login to admin

**Expected behavior**
See the dashboard

**Screenshots**
![image](https://github.com/realodix/urlhub/assets/832259/0207c349-ec76-4100-bd5b-064b1493fb8c)

**Comment by realodix** [comment]
Sorry, I cannot reproduce it. It looks like the issue is with livewire.
